services:
    glavweb_rest.security_access_handler:
        class:  Glavweb\RestBundle\Security\AccessHandler
        arguments: ["@annotation_reader"]

    glavweb_rest.security_access_rest_voter:
        class:  Glavweb\RestBundle\Security\Authorization\Voter\RestVoter
        arguments: ["@doctrine", "@glavweb_rest.security_access_handler"]
        public: false
        tags:
           - { name: security.voter }

    glavweb_rest.editable_role_builder:
        class: Glavweb\RestBundle\Security\EditableRolesBuilder
        arguments: ["@security.context", "@doctrine", "@glavweb_rest.security_access_handler", "%security.role_hierarchy.roles%"]

    glavweb_rest.form_type_security_roles:
        class: Glavweb\RestBundle\Form\SecurityRolesType
        arguments: ["@glavweb_rest.editable_role_builder"]
        tags:
            - {name: form.type, alias: glavweb_security_roles}

    glavweb_rest.admin_security_handler_role:
        class: Glavweb\RestBundle\Admin\SecurityHandlerRole
        arguments: ["@security.context", "@glavweb_rest.security_access_handler", [ROLE_SUPER_ADMIN]]

    glavweb_rest.form_action:
        class: Glavweb\RestBundle\Action\RestFormAction
        calls:
            - [setDoctrine, ["@doctrine"]]
            - [setSecurityContext, ["@security.context"]]
            - [setFormFactory, ["@form.factory"]]

    glavweb_rest.file_faker:
        class: Glavweb\RestBundle\Faker\FileFaker
        arguments: ["@kernel", "%kernel.root_dir%"]

    glavweb_rest.test_determiner_handler:
        class: Glavweb\RestBundle\Determiner\DeterminerHandler
        arguments: ["@kernel", "@doctrine", "@form.factory", "@jms_serializer.metadata.doctrine_type_driver"]

    glavweb_rest.create_action_determiner:
        class: Glavweb\RestBundle\Determiner\Action\CreateActionDeterminer
        arguments: ["@glavweb_rest.test_determiner_handler", "@glavweb_rest.file_faker"]

    glavweb_rest.view_action_determiner:
        class: Glavweb\RestBundle\Determiner\Action\ViewActionDeterminer
        arguments: ["@glavweb_rest.test_determiner_handler", "@doctrine"]

    glavweb_rest.list_action_determiner:
        class: Glavweb\RestBundle\Determiner\Action\ListActionDeterminer
        arguments: ["@glavweb_rest.test_determiner_handler", "@router", "@fos_rest.request.param_fetcher.reader"]

    glavweb_rest.update_action_determiner:
        class: Glavweb\RestBundle\Determiner\Action\UpdateActionDeterminer
        arguments: ["@glavweb_rest.test_determiner_handler"]

    glavweb_rest.patch_action_determiner:
        class: Glavweb\RestBundle\Determiner\Action\PatchActionDeterminer
        arguments: ["@glavweb_rest.test_determiner_handler"]
